### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MalurixGaming** [Patai5/BakaBot#11]
Can you help me? This write on start..

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\simdu\Downloads\BakaBot-main\env\lib\site-packages\disnake\client.py", line 703, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\simdu\Downloads\BakaBot-main\src\BakaBot\main.py", line 34, in on_ready
    startedSuccessfully = await first_time_setup.start(client)
  File "C:\Users\simdu\Downloads\BakaBot-main\src\BakaBot\utils\first_time_setup.py", line 60, in start
    schedule1 = await Schedule.get_schedule(False, client)
  File "C:\Users\simdu\Downloads\BakaBot-main\src\BakaBot\core\schedule\schedule.py", line 128, in get_schedule
    return parseSchedule(html, nextWeek)
  File "C:\Users\simdu\Downloads\BakaBot-main\src\BakaBot\core\schedule\parse_schedule.py", line 25, in parseSchedule
    return Schedule(parseDays(daysEls), nextWeek)
  File "C:\Users\simdu\Downloads\BakaBot-main\src\BakaBot\core\schedule\parse_schedule.py", line 31, in parseDays
    return [parseDay(day) for day in daysEls]
  File "C:\Users\simdu\Downloads\BakaBot-main\src\BakaBot\core\schedule\parse_schedule.py", line 31, in <listcomp>
    return [parseDay(day) for day in daysEls]
  File "C:\Users\simdu\Downloads\BakaBot-main\src\BakaBot\core\schedule\parse_schedule.py", line 46, in parseDay
    weekDay = DAYS[weekDay]
KeyError: 'e'

**Comment by Patai5** [comment]
Dobry den, diky za report!

Mam ted skoro stejny error kvuli prazdninam :D Az nastane skolni rok s normalnim rozvrhem tak uz by to melo fungovat 🤞 

---
V mem pripade mi to failuje protoze pristi tyden v rozvrhu ma z nejakeho duvodu jenom sobotu??
![image](https://github.com/user-attachments/assets/aec89839-a598-40cb-983c-dbe740230859)

Jinak ve vasem pripade tam je pry nejaky den ktery se jmenuje "e"? To bude snad taky kvuli prazdninam :D

Kdyztak staci zmenit par hodnot v tomhle super nahardcodovanem filu pro vasi instanci bakalaru:
https://github.com/Patai5/BakaBot/blob/fb1d57c46be2ba1cd7152e19848af6f825cfdbbb/src/bakabot/constants.py#L1-L8

Toho souboru se postupne zbavuju a scrapuju dynamicky, ale ted pres leto jsem jeho demolici odlozil, protoze bez funkcnich bakalaru se to docela obtizne testuje no... :D

---
Necham tohle issue prozatim otevrene, kdyby vam bot nefungoval ani s funkcnim rozvrhem tak se k tomu vratim :) Diky!

**Comment by MalurixGaming** [comment]
Ok, děkuji za odpověď, v příštím týdnu to vyzkouším. 👍
Malurix.

**Comment by MalurixGaming** [comment]
Když jsem dnes spustil BakaBota, tak mi napsal chybu.. Pomohl by jsi mi s ním prosím?

Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/raspberrypi/BakaBot/env/lib/python3.11/site-packages/disnake/client.py", line 703, in _run_event
    await coro(*args, **kwargs)
  File "/home/raspberrypi/BakaBot/src/bakabot/main.py", line 34, in on_ready
    startedSuccessfully = await first_time_setup.start(client)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspberrypi/BakaBot/src/bakabot/utils/first_time_setup.py", line 70, in start
    grades = await Grades.getGrades(client)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspberrypi/BakaBot/src/bakabot/core/grades/grades.py", line 120, in getGrades
    return parseGrades(gradesResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raspberrypi/BakaBot/src/bakabot/core/grades/parse_grades.py", line 15, in parseGrades
    raise ValueError("Could not find main data script for grades")
ValueError: Could not find main data script for grades

**Comment by Patai5** [comment]
Aha, tohle je ale docela jasne (snad) :D Ocividne v kodu pocitam s tim ze bude mit uzivatel na bakalarich aspon jednu znamku, coz samozrejme prvni den skoly moc lidi mit nebude :P Taky je to asi hodne low priority issue, se kterym se mi nechce moc stvat jenom aby bakabot fungoval prvni tyden skoly...

Uplne ez fix je prozatim proste odstranit tuhle linu:
https://github.com/Patai5/BakaBot/blob/fb1d57c46be2ba1cd7152e19848af6f825cfdbbb/src/bakabot/main.py#L68
Tim se vypne detekce znamek a s tim i tenhle bug :)

---

Ja ted bota na svych bakalarich nemuzu ted moc otestovat, protoze jako vzdy samozrejme vyborne funguji:
![image](https://github.com/user-attachments/assets/70b4a4f9-3b67-430b-904c-163024c81e70)
(miluju bakalare :))))

---

Jeste je teda taky mozne, ze je proste vase instance bakalaru dostatecne jina a ta extrakce dat failuje, ale o tom docela pochybuji (na to jsou bakalari az moc shit). Podle me to fungovat se znamkama uz snad konecne bude 🤞 Diky!

**Comment by Patai5** [comment]
Ok, uz nam bezi bakalari tak to muzu konecne otestovat :) Mam ten stejny error a presne 0 znamek.

Jeste je teda potreba odstranit tyhle liny:
https://github.com/Patai5/BakaBot/blob/fb1d57c46be2ba1cd7152e19848af6f825cfdbbb/src/bakabot/utils/first_time_setup.py#L69-L76

Nebo tu podminku proste vypnout:
 ```py
if False: 
    grades = await Grades.getGrades(client)
    ...
```

Pak uz mi, az na znamky teda, bezi bot tak jak ma :)

**Comment by MalurixGaming** [comment]
Už funguje, děkuji moc za pomoc, jen jsem se chtěl zeptat, co přesně má dělat ten příkaz get_subjects?

**Comment by Patai5** [comment]
To je spis debugovaci prikaz, vzasade jenom vypise vsechny ulozene predemety v databazi.
<img width="414" alt="image" src="https://github.com/user-attachments/assets/6bc6864b-dd39-4327-9001-c31b72b76962">

(on ma bot docela sloziout interni logiku s tema predmetama, protoze z rozvrhu se da ziskat kratky i dlouhy nazev predmetu, ale ze znamek jenom dlouhy (myslim?). Tak to pak mezi znamkama a rozvrhem synchronizuju protoze se mi na nekterych mistech ty libi vic ty kratsi nazvy ve zkratkach.)

**Comment by MalurixGaming** [comment]
Chápu, děkuji moc

**Comment by Patai5** [comment]
Dobry den, na nase bakalare uz prisli nejake znamky a bot s nimi funguje tak jak ma.

Funguje extrakce znamek i z vasich bakalaru? Prozatim toto issue uzaviram, diky!
